TrajectoryPlannerROS:
   max_vel_x: 0.80
   min_vel_y: 0.10
   max_vel_theta: 0.8
   min_vel_theta: -0.8
   min_in_place_vel_theta: 0.3

   acc_lim_theta: 3.2
   acc_lim_x: 1.5
   acc_lim_y: 1.5

   escape_vel: -0.2

   holonomic_robot: false

   sim_time: 2.0
   dwa: true

   pdist_scale: 0.3
   gdist_scale: 0.3
   occdist_scale: 0.03

   xy_goal_tolerance: 0.25
   yaw_goal_tolerance: 0.10

   meter_scoring: true
