global_frame: odom
update_frequency: 8.0
publish_frequency: 2.0
rolling_window: true
width: 5.0
height: 5.0
resolution: 0.05 #guess

plugins:
#   - name: sonar_layer
#     type: "sonar_layer::SonarLayer"
   - name: obstacle_layer
     type: "costmap_2d::ObstacleLayer"
   - name: footprint_layer
     type: "costmap_2d::FootprintLayer"
   - name: inflation_layer
     type: "costmap_2d::InflationLayer"